//! Preset (named) color value enumeration for `DrawingML`.

/// Preset (named) color value (`<a:prstClr val="...">`).
/// Unknown values are preserved via the `Other` variant.
#[non_exhaustive]
#[repr(u8)]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PresetColorVal {
    AliceBlue,
    AntiqueWhite,
    Aqua,
    Aquamarine,
    Azure,
    Beige,
    Bisque,
    Black,
    BlanchedAlmond,
    Blue,
    BlueViolet,
    Brown,
    BurlyWood,
    CadetBlue,
    Chartreuse,
    Chocolate,
    Coral,
    CornflowerBlue,
    Cornsilk,
    Crimson,
    Cyan,
    DarkBlue,
    DarkCyan,
    DarkGoldenrod,
    DarkGray,
    DarkGreen,
    DarkKhaki,
    DarkMagenta,
    DarkOliveGreen,
    DarkOrange,
    DarkOrchid,
    DarkRed,
    DarkSalmon,
    DarkSeaGreen,
    DarkSlateBlue,
    DarkSlateGray,
    DarkTurquoise,
    DarkViolet,
    DeepPink,
    DeepSkyBlue,
    DimGray,
    DodgerBlue,
    Firebrick,
    FloralWhite,
    ForestGreen,
    Fuchsia,
    Gainsboro,
    GhostWhite,
    Gold,
    Goldenrod,
    Gray,
    Green,
    GreenYellow,
    Honeydew,
    HotPink,
    IndianRed,
    Indigo,
    Ivory,
    Khaki,
    Lavender,
    LavenderBlush,
    LawnGreen,
    LemonChiffon,
    LightBlue,
    LightCoral,
    LightCyan,
    LightGoldenrodYellow,
    LightGray,
    LightGreen,
    LightPink,
    LightSalmon,
    LightSeaGreen,
    LightSkyBlue,
    LightSlateGray,
    LightSteelBlue,
    LightYellow,
    Lime,
    LimeGreen,
    Linen,
    Magenta,
    Maroon,
    MedAquamarine,
    MedBlue,
    MedOrchid,
    MedPurple,
    MedSeaGreen,
    MedSlateBlue,
    MedSpringGreen,
    MedTurquoise,
    MedVioletRed,
    MidnightBlue,
    MintCream,
    MistyRose,
    Moccasin,
    NavajoWhite,
    Navy,
    OldLace,
    Olive,
    OliveDrab,
    Orange,
    OrangeRed,
    Orchid,
    PaleGoldenrod,
    PaleGreen,
    PaleTurquoise,
    PaleVioletRed,
    PapayaWhip,
    PeachPuff,
    Peru,
    Pink,
    Plum,
    PowderBlue,
    Purple,
    Red,
    RosyBrown,
    RoyalBlue,
    SaddleBrown,
    Salmon,
    SandyBrown,
    SeaGreen,
    SeaShell,
    Sienna,
    Silver,
    SkyBlue,
    SlateBlue,
    SlateGray,
    Snow,
    SpringGreen,
    SteelBlue,
    Tan,
    Teal,
    Thistle,
    Tomato,
    Turquoise,
    Violet,
    Wheat,
    White,
    WhiteSmoke,
    Yellow,
    YellowGreen,
    /// Unknown / unrecognised preset color value preserved for round-tripping.
    Other(String),
}

impl PresetColorVal {
    /// Return the XML attribute value for this preset color.
    // exhaustive enum conversion
    #[allow(clippy::too_many_lines)]
    #[must_use]
    pub fn to_xml_str(&self) -> &str {
        match self {
            Self::AliceBlue => "aliceBlue",
            Self::AntiqueWhite => "antiqueWhite",
            Self::Aqua => "aqua",
            Self::Aquamarine => "aquamarine",
            Self::Azure => "azure",
            Self::Beige => "beige",
            Self::Bisque => "bisque",
            Self::Black => "black",
            Self::BlanchedAlmond => "blanchedAlmond",
            Self::Blue => "blue",
            Self::BlueViolet => "blueViolet",
            Self::Brown => "brown",
            Self::BurlyWood => "burlyWood",
            Self::CadetBlue => "cadetBlue",
            Self::Chartreuse => "chartreuse",
            Self::Chocolate => "chocolate",
            Self::Coral => "coral",
            Self::CornflowerBlue => "cornflowerBlue",
            Self::Cornsilk => "cornsilk",
            Self::Crimson => "crimson",
            Self::Cyan => "cyan",
            Self::DarkBlue => "dkBlue",
            Self::DarkCyan => "dkCyan",
            Self::DarkGoldenrod => "dkGoldenrod",
            Self::DarkGray => "dkGray",
            Self::DarkGreen => "dkGreen",
            Self::DarkKhaki => "dkKhaki",
            Self::DarkMagenta => "dkMagenta",
            Self::DarkOliveGreen => "dkOliveGreen",
            Self::DarkOrange => "dkOrange",
            Self::DarkOrchid => "dkOrchid",
            Self::DarkRed => "dkRed",
            Self::DarkSalmon => "dkSalmon",
            Self::DarkSeaGreen => "dkSeaGreen",
            Self::DarkSlateBlue => "dkSlateBlue",
            Self::DarkSlateGray => "dkSlateGray",
            Self::DarkTurquoise => "dkTurquoise",
            Self::DarkViolet => "dkViolet",
            Self::DeepPink => "deepPink",
            Self::DeepSkyBlue => "deepSkyBlue",
            Self::DimGray => "dimGray",
            Self::DodgerBlue => "dodgerBlue",
            Self::Firebrick => "firebrick",
            Self::FloralWhite => "floralWhite",
            Self::ForestGreen => "forestGreen",
            Self::Fuchsia => "fuchsia",
            Self::Gainsboro => "gainsboro",
            Self::GhostWhite => "ghostWhite",
            Self::Gold => "gold",
            Self::Goldenrod => "goldenrod",
            Self::Gray => "gray",
            Self::Green => "green",
            Self::GreenYellow => "greenYellow",
            Self::Honeydew => "honeydew",
            Self::HotPink => "hotPink",
            Self::IndianRed => "indianRed",
            Self::Indigo => "indigo",
            Self::Ivory => "ivory",
            Self::Khaki => "khaki",
            Self::Lavender => "lavender",
            Self::LavenderBlush => "lavenderBlush",
            Self::LawnGreen => "lawnGreen",
            Self::LemonChiffon => "lemonChiffon",
            Self::LightBlue => "ltBlue",
            Self::LightCoral => "ltCoral",
            Self::LightCyan => "ltCyan",
            Self::LightGoldenrodYellow => "ltGoldenrodYellow",
            Self::LightGray => "ltGray",
            Self::LightGreen => "ltGreen",
            Self::LightPink => "ltPink",
            Self::LightSalmon => "ltSalmon",
            Self::LightSeaGreen => "ltSeaGreen",
            Self::LightSkyBlue => "ltSkyBlue",
            Self::LightSlateGray => "ltSlateGray",
            Self::LightSteelBlue => "ltSteelBlue",
            Self::LightYellow => "ltYellow",
            Self::Lime => "lime",
            Self::LimeGreen => "limeGreen",
            Self::Linen => "linen",
            Self::Magenta => "magenta",
            Self::Maroon => "maroon",
            Self::MedAquamarine => "medAquamarine",
            Self::MedBlue => "medBlue",
            Self::MedOrchid => "medOrchid",
            Self::MedPurple => "medPurple",
            Self::MedSeaGreen => "medSeaGreen",
            Self::MedSlateBlue => "medSlateBlue",
            Self::MedSpringGreen => "medSpringGreen",
            Self::MedTurquoise => "medTurquoise",
            Self::MedVioletRed => "medVioletRed",
            Self::MidnightBlue => "midnightBlue",
            Self::MintCream => "mintCream",
            Self::MistyRose => "mistyRose",
            Self::Moccasin => "moccasin",
            Self::NavajoWhite => "navajoWhite",
            Self::Navy => "navy",
            Self::OldLace => "oldLace",
            Self::Olive => "olive",
            Self::OliveDrab => "oliveDrab",
            Self::Orange => "orange",
            Self::OrangeRed => "orangeRed",
            Self::Orchid => "orchid",
            Self::PaleGoldenrod => "paleGoldenrod",
            Self::PaleGreen => "paleGreen",
            Self::PaleTurquoise => "paleTurquoise",
            Self::PaleVioletRed => "paleVioletRed",
            Self::PapayaWhip => "papayaWhip",
            Self::PeachPuff => "peachPuff",
            Self::Peru => "peru",
            Self::Pink => "pink",
            Self::Plum => "plum",
            Self::PowderBlue => "powderBlue",
            Self::Purple => "purple",
            Self::Red => "red",
            Self::RosyBrown => "rosyBrown",
            Self::RoyalBlue => "royalBlue",
            Self::SaddleBrown => "saddleBrown",
            Self::Salmon => "salmon",
            Self::SandyBrown => "sandyBrown",
            Self::SeaGreen => "seaGreen",
            Self::SeaShell => "seaShell",
            Self::Sienna => "sienna",
            Self::Silver => "silver",
            Self::SkyBlue => "skyBlue",
            Self::SlateBlue => "slateBlue",
            Self::SlateGray => "slateGray",
            Self::Snow => "snow",
            Self::SpringGreen => "springGreen",
            Self::SteelBlue => "steelBlue",
            Self::Tan => "tan",
            Self::Teal => "teal",
            Self::Thistle => "thistle",
            Self::Tomato => "tomato",
            Self::Turquoise => "turquoise",
            Self::Violet => "violet",
            Self::Wheat => "wheat",
            Self::White => "white",
            Self::WhiteSmoke => "whiteSmoke",
            Self::Yellow => "yellow",
            Self::YellowGreen => "yellowGreen",
            Self::Other(s) => s.as_str(),
        }
    }
}
